feat(env): implement static environment loading     - Introduce  struct to hold shell state and memory cursors.     - Implement  to copy environment variables into the static .     - Add  in  to safely copy strings to the buffer with overflow      protection.     - Update  to initialize the shell structure and load the environment.     - Add  and update [34m---- Running static analisys ----[0m
[34m---- Running norminette ----[0m
Error: '../main.c' no such file or directory
[31mNorminette not passed[0m

[34m---- Running init_env unit tests ----[0m
Failed to make targets for validation.
    - Replace binary test file  with  for buffer limit testing.